name=GSMController
version=1.0.0
author=Odon Cândido
maintainer=Odon
sentence=Controle de Modulo GSM baseados em SIM800L
paragraph=Biblioteca para controle de módulos GSM baseados no SIM800L através de comandos AT.
category=Device Control
url=https://127.0.0.2/
architectures=esp32
